type_adv = {
        ('normal',  'rock'): .5,
        ('normal',  'ghost'): 0,
        ('normal',  'steel'): .5,

        ('fight',  'normal'): 2,
        ('fight', 'flying'): .5,
        ('fight', 'poison'): .5,
        ('fight', 'rock'): 2,
        ('fight', 'rock'): 2,
        ('fight', 'bug'): .5,
        ('fight', 'ghost'): 0,
        ('fight', 'steel'): 2,
        ('fight', 'psychic'): .5,
        ('fight', 'ice'): 2,
        ('fight', 'dark'): 2,
        ('fight', 'fairy'): .5,


        ('flying', 'fight'): 2,
        ('flying', 'rock'): .5,
        ('flying', 'bug'): 2,
        ('flying', 'steel'): .5,
        ('flying', 'grass'): 2,
        ('flying', 'electric'): .5,

        ('poison', 'poison'): .5,
        ('poison', 'ground'): .5,
        ('poison', 'rock'): .5,
        ('poison', 'ghost'): .5,
        ('poison', 'steel'): 0,
        ('poison', 'grass'): 2,
        ('poison', 'fairy'): 2,

        ('ground', 'flying'): 0,
        ('ground', 'poison'): 2,
        ('ground', 'rock'): 2,
        ('ground', 'bug'): .5,
        ('ground', 'steel'): 2,
        ('ground', 'fire'): 2,
        ('ground', 'grass'): .5,
        ('ground', 'electric'): 2,

        ('rock', 'fight'): .5,
        ('rock', 'flying'): 2,
        ('rock', 'ground'): .5,
        ('rock', 'bug'): 2,
        ('rock', 'steel'): .5,
        ('rock', 'fire'): 2,
        ('rock', 'ice'): 2,

        ('bug', 'fight'): .5,
        ('bug', 'flying'): .5,
        ('bug', 'poison'): .5,
        ('bug', 'ghost'): .5,
        ('bug', 'steel'): .5,
        ('bug', 'fire'): .5,
        ('bug', 'grass'): 2,
        ('bug', 'psychic'): 2,
        ('bug', 'dark'): 2,
        ('bug', 'fairy'): .5,

        ('ghost', 'normal'): 0,
        ('ghost', 'ghost'): 2,
        ('ghost', 'psychic'): 2,
        ('ghost', 'dark'): .5,

        ('steel', 'rock'): 2,
        ('steel', 'steel'): .5,
        ('steel', 'fire'): .5,
        ('steel', 'water'): .5,
        ('steel', 'electric'): .5,
        ('steel', 'ice'): 2,
        ('steel', 'fairy'): 2,

        ('fire', 'rock'): .5,
        ('fire', 'bug'): 2,
        ('fire', 'steel'): 2,
        ('fire', 'fire'): .5,
        ('fire', 'water'): .5,
        ('fire', 'grass'): 2,
        ('fire', 'ice'): 2,
        ('fire', 'dragon'): .5,

        ('water', 'ground'): 2,
        ('water', 'rock'): 2,
        ('water', 'fire'): 2,
        ('water', 'water'): .5,
        ('water', 'grass'): .5,
        ('water', 'dragon'): .5,

        ('grass', 'flying'): .5,
        ('grass', 'poison'): .5,
        ('grass', 'ground'): 2,
        ('grass', 'rock'): 2,
        ('grass', 'bug'): .5,
        ('grass', 'steel'): .5,
        ('grass', 'fire'): .5,
        ('grass', 'water'): 2,
        ('grass', 'grass'): .5,
        ('grass', 'dragon'): .5,

        ('electric', 'flying'): 2,
        ('electric', 'ground'): 0,
        ('electric', 'water'): 2,
        ('electric', 'grass'): .5,
        ('electric', 'electric'): .5,
        ('electric', 'dragon'): .5,

        ('psychic', 'fight'): 2,
        ('psychic', 'poison'): 2,
        ('psychic', 'steel'): .5,
        ('psychic', 'psychic'): .5,
        ('psychic', 'dark'): 0,

        ('ice', 'flying'): 2,
        ('ice', 'ground'): 2,
        ('ice', 'steel'): .5,
        ('ice', 'fire'): .5,
        ('ice', 'water'): .5,
        ('ice', 'grass'): 2,
        ('ice', 'ice'): .5,
        ('ice', 'dragon'): 2,

        ('dragon', 'steek'): .5,
        ('dragon', 'dragon'): 2,
        ('dragon', 'fairy'): 0,

        ('dark', 'fight'): .5,
        ('dark', 'ghost'): 2,
        ('dark', 'psychic'): 2,
        ('dark', 'dark'): .5,
        ('dark', 'fairy'): .5,

        ('fairy', 'fight'): 2,
        ('fairy', 'poison'): .5,
        ('fairy', 'steel'): .5,
        ('fairy', 'fire'): .5,
        ('fairy', 'dragon'): 2,
        ('fairy', 'dark'): 2,
}
